// Generated by https://quicktype.io

export class RecentlyPlayed {
    items:   Item[];
    next:    string;
    cursors: Cursors;
    limit:   number;
    href:    string;
}

export class Cursors {
    after:  string;
    before: string;
}

export class Item {
    track:     Track;
    played_at: string;
    context:   Context | null;
}

export class Context {
    uri:           string;
    external_urls: ExternalUrls;
    href:          string;
    type:          ContextType;
}

export class ExternalUrls {
    spotify: string;
}

export enum ContextType {
    Artist = "artist",
}

export class Track {
    album:             Album;
    artists:           Artist[];
    available_markets: string[];
    disc_number:       number;
    duration_ms:       number;
    explicit:          boolean;
    external_ids:      ExternalIDS;
    external_urls:     ExternalUrls;
    href:              string;
    id:                string;
    is_local:          boolean;
    name:              string;
    popularity:        number;
    preview_url:       string;
    track_number:      number;
    type:              TrackType;
    uri:               string;
}

export class Album {
    album_type:             AlbumTypeEnum;
    artists:                Artist[];
    available_markets:      string[];
    external_urls:          ExternalUrls;
    href:                   string;
    id:                     string;
    images:                 Image[];
    name:                   string;
    release_date:           string;
    release_date_precision: ReleaseDatePrecision;
    total_tracks:           number;
    type:                   AlbumTypeEnum;
    uri:                    string;
}

export enum AlbumTypeEnum {
    Album = "album",
    Single = "single",
}

export class Artist {
    external_urls: ExternalUrls;
    href:          string;
    id:            string;
    name:          string;
    type:          ContextType;
    uri:           string;
}

export class Image {
    height: number;
    url:    string;
    width:  number;
}

export enum ReleaseDatePrecision {
    Day = "day",
}

export class ExternalIDS {
    isrc: string;
}

export enum TrackType {
    Track = "track",
}
