// Generated by https://quicktype.io

export class Playlist {
    href:     string;
    items:    Item[];
    limit:    number;
    next:     string;
    offset:   number;
    previous: null;
    total:    number;
}

export class Item {
    collaborative: boolean;
    external_urls: ExternalUrls;
    href:          string;
    id:            string;
    images:        Image[];
    name:          string;
    owner:         Owner;
    primary_color: null;
    public:        boolean;
    snapshot_id:   string;
    tracks:        Tracks;
    type:          ItemType;
    uri:           string;
}

export class ExternalUrls {
    spotify: string;
}

export class Image {
    height: number | null;
    url:    string;
    width:  number | null;
}

export class Owner {
    display_name:  string;
    external_urls: ExternalUrls;
    href:          string;
    id:            string;
    type:          OwnerType;
    uri:           string;
}

export enum OwnerType {
    User = "user",
}

export class Tracks {
    href:  string;
    total: number;
}

export enum ItemType {
    Playlist = "playlist",
}
